//1
//0
//1
//146
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
  
using System.Resources;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("EcSolvo.RestHelper")]
[assembly: AssemblyDescription("RestHelper is a sleek and simple Wrapper library for providing simple access to Rest API, by hiding away the complexities of HTTPClient Class.It is particularly designed to work along with Xamarin PCL Projects")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("EcSolvo Technologies")]
[assembly: AssemblyProduct("RestHelper")]
[assembly: AssemblyCopyright("Copyright © EcSolvo Technologies 2017")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: NeutralResourcesLanguage("en")]

[assembly: AssemblyVersion("1.0.1.146")]